import { ChildData } from "./PersonalData";
import { tr } from "date-fns/locale";
export default function AcademicHistory() {
  const arr: ChildData[] = [
    {
      type: "check",
      id: "stayGrade",
      lable: "האם הילד נשאר שנתיים באותה כיתה?",
      condition: false,
    },
    {
      type: "text",
      id: "whichGrade",
      lable: "באיזה כיתה?",
      condition: true,
      conditionById: ["stayGrade"],
    },
    {
      type: "textArea",
      id: "stayGradeReasons",
      lable: "מאלו סיבות?",
      condition: true,
      conditionById: ["stayGrade"],
    },
    {
      type: "check",
      id: "learningDeficits",
      lable: "האם אתם מרגישים שלילד שלכם יש קשיים בלמידה?",
      condition: false,
    },

    {
      type: "textArea",
      id: "learningDeficitsKind",
      lable: "מאיזה סוג",
      condition: true,
      conditionById: ["learningDeficits"],
    },
    {
      type: "text",
      id: "learningDeficitsKindStart",
      lable: "מתי (השנה) התחילו הקשיים האלו?",
      kind: "text",
      condition: true,
      conditionById: ["learningDeficits"],
    },
    {
      type: "label",
      lable: "האם אתה רואה את ילדך כ-",
      condition: false,
    },
    {
      type: "radio",
      id: "distracted",
      lable: "מוסח",
      childrenLables: [
        { id: "distractedYes", lable: "כן" },
        { id: "distractedSometimes", lable: "לפעמים" },
        { id: "distractedNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "restless",
      lable: "חסר מנוחה",
      childrenLables: [
        { id: "restlessYes", lable: "כן" },
        { id: "restlessSometimes", lable: "לפעמים" },
        { id: "restlessNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "distorted",
      lable: "משבש",
      childrenLables: [
        { id: "distortedYes", lable: "כן" },
        { id: "distortedSometimes", lable: "לפעמים" },
        { id: "distortedNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "textArea",
      id: "activeComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "label",
      lable: "האם אתם מודאגים לליקויים של הילד בתחומים האלה?",
      condition: false,
    },
    {
      type: "radio",
      id: "attention",
      lable: "תשומת לב",
      childrenLables: [
        { id: "attentionYes", lable: "כן" },
        { id: "attentionSometimes", lable: "לפעמים" },
        { id: "attentionNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "newLearning",
      lable: "למידה של חומר חדש",
      childrenLables: [
        { id: "newLearningYes", lable: "כן" },
        { id: "newLearningSometimes", lable: "לפעמים" },
        { id: "newLearningNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "memory",
      lable: "זיכרון",
      childrenLables: [
        { id: "memoryYes", lable: "כן" },
        { id: "memorySometimes", lable: "לפעמים" },
        { id: "memoryNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "autonomy",
      lable: "אוטונומיה",
      childrenLables: [
        { id: "autonomyYes", lable: "כן" },
        { id: "autonomySometimes", lable: "לפעמים" },
        { id: "autonomyNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "motorSkills",
      lable: "מיומנויות מוטוריות",
      childrenLables: [
        { id: "motorSkillsYes", lable: "כן" },
        { id: "motorSkillsSometimes", lable: "לפעמים" },
        { id: "motorSkillsNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "radio",
      id: "confidence",
      lable: "ביטחון עצמי/הערכה עצמית",
      childrenLables: [
        { id: "confidenceYes", lable: "כן" },
        { id: "confidenceSometimes", lable: "לפעמים" },
        { id: "confidenceNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "textArea",
      id: "defectsComments",
      lable: "אחר/הערות",
      condition: false,
    },
    {
      type: "label",
      lable: "האם אתם מודאגים לליקויים של הילד בכלים האלה?",
      condition: false,
    },
    {
      type: "check",
      id: "graphics",
      lable: "גרפיקה",
      condition: false,
    },
    {
      type: "check",
      id: "math",
      lable: "חשבון",
      condition: false,
    },
    {
      type: "check",
      id: "expression ",
      lable: "הבעה",
      condition: false,
    },
    {
      type: "check",
      id: "writing",
      lable: "כתיבה",
      condition: false,
    },
    {
      type: "check",
      id: "reading",
      lable: "קריאה",
      condition: false,
    },
    {
      type: "textArea",
      id: "anotherSubject",
      lable: "אחר",
      condition: false,
    },
    {
      type: "label",
      lable: "האם הילד קיבל עזרה/טיפול או חונך מחדש על ידי:",
      condition: false,
    },
    {
      type: "radio",
      id: "privateTeacher",
      lable: "האם הילד קיבל שיעורי עזר בבית ספר/מורה פרטי?",
      childrenLables: [
        { id: "privateTeacherYes", lable: "כן" },
        { id: "privateTeacherSometimes", lable: "לפעמים" },
        { id: "privateTeacherNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "text",
      id: "privateTeacherSubject",
      lable: "באיזה מקצוע?",
      kind: "text",
      condition: true,
      conditionById: ["privateTeacher"],
      conditionByIdValueRadio:["privateTeacherYes","privateTeacherSometimes"]
    },
    {
      type: "textArea",
      id: "privateTeacherComments",
      lable: "הערות",
      condition: true,
      conditionById: ["privateTeacher"],
      conditionByIdValueRadio:["privateTeacherYes","privateTeacherSometimes"]
    },
    {
      type: "check",
      id: "occupationalTherapist",
      lable: "מרפא בעיסוק",
      condition: false,
    },
    {
      type: "text",
      id: "occupationalTherapistAge",
      lable: "באיזה גיל/כיתה?",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapist"],
    },
    {
      type: "text",
      id: "occupationalTherapistTime",
      lable: "לכמה זמן?",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapist"],
    },
    {
      type: "text",
      id: "occupationalTherapistName",
      lable: "שם המרפא",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapist"],
    },
    {
      type: "text",
      id: "occupationalTherapistCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapist"],
    },
    {
      type: "check",
      id: "communicationClinician",
      lable: "קלינאי תקשורת",
      condition: false,
    },
    {
      type: "text",
      id: "communicationClinicianAge",
      lable: "באיזה גיל/כיתה?",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinician"],
    },
    {
      type: "text",
      id: "communicationClinicianTime",
      lable: "לכמה זמן?",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinician"],
    },
    {
      type: "text",
      id: "communicationClinicianName",
      lable: "שם הקלינאי",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinician"],
    },
    {
      type: "text",
      id: "communicationClinicianCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinician"],
    },
    {
      type: "check",
      id: "correctiveTeacher",
      lable: "מורה מתקנת",
      condition: false,
    },
    {
      type: "text",
      id: "correctiveTeacherAge",
      lable: "באיזה גיל/כיתה?",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacher"],
    },
    {
      type: "text",
      id: "correctiveTeacherTime",
      lable: "לכמה זמן?",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacher"],
    },
    {
      type: "text",
      id: "correctiveTeacherName",
      lable: "שם המורה",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacher"],
    },
    {
      type: "text",
      id: "correctiveTeacherCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacher"],
    },
    {
      type: "check",
      id: "psychologist",
      lable: "פסיכולוג",
      condition: false,
    },
    {
      type: "text",
      id: "psychologistAge",
      lable: "באיזה גיל/כיתה?",
      kind: "text",
      condition: true,
      conditionById: ["psychologist"],
    },
    {
      type: "text",
      id: "psychologistTime",
      lable: "לכמה זמן?",
      kind: "text",
      condition: true,
      conditionById: ["psychologist"],
    },
    {
      type: "text",
      id: "psychologistName",
      lable: "שם הפסיכולוג",
      kind: "text",
      condition: true,
      conditionById: ["psychologist"],
    },
    {
      type: "text",
      id: "psychologistCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["psychologist"],
    },
    {
      type: "check",
      id: "Orthoptics",
      lable: "אורתופטיקה",
      condition: false,
    },
    {
      type: "text",
      id: "OrthopticsAge",
      lable: "באיזה גיל/כיתה?",
      kind: "text",
      condition: true,
      conditionById: ["Orthoptics"],
    },
    {
      type: "text",
      id: "OrthopticsTime",
      lable: "לכמה זמן?",
      kind: "text",
      condition: true,
      conditionById: ["Orthoptics"],
    },
    {
      type: "text",
      id: "OrthopticsName",
      lable: "שם הרופא",
      kind: "text",
      condition: true,
      conditionById: ["Orthoptics"],
    },
    {
      type: "text",
      id: "OrthopticsCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["Orthoptics"],
    },
    {
      type: "textArea",
      id: "otherTreatment",
      lable: "אחר-לפרט",
      condition: false
    },
    {
      type: "label",
      lable: "האם הילד מקבל כעת עזרה/טיפול או חונך מחדש על ידי:",
      condition: false,
    },
    {
      type: "radio",
      id: "privateTeacherNow",
      lable: "האם הילד מקבל כעת שיעורי עזר בבית ספר/מורה פרטי?",
      childrenLables: [
        { id: "privateTeacherNowYes", lable: "כן" },
        { id: "privateTeacherNowSometimes", lable: "לפעמים" },
        { id: "privateTeacherNowNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "text",
      id: "privateTeacherNowSubject",
      lable: "באיזה מקצוע?",
      kind: "text",
      condition: true,
      conditionById: ["privateTeacherNow"],
      conditionByIdValueRadio:["privateTeacherNowYes","privateTeacherNowSometimes"]
    },
    {
      type: "textArea",
      id: "privateTeacherNowComments",
      lable: "הערות",
      condition: true,
      conditionById: ["privateTeacherNow"],
      conditionByIdValueRadio:["privateTeacherNowYes","privateTeacherNowSometimes"]
    },
    {
      type: "check",
      id: "occupationalTherapistNow",
      lable: "מרפא בעיסוק",
      condition: false,
    },
    {
      type: "text",
      id: "occupationalTherapistNowWhen",
      lable: "ממתי?",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapistNow"],
    },
    {
      type: "text",
      id: "occupationalTherapistNowName",
      lable: "שם המרפא",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapistNow"],
    },
    {
      type: "text",
      id: "occupationalTherapistNowCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["occupationalTherapistNow"],
    },
    {
      type: "check",
      id: "communicationClinicianNow",
      lable: "קלינאי תקשורת",
      condition: false,
    },
    {
      type: "text",
      id: "communicationClinicianNowWhen",
      lable: "ממתי?",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinicianNow"],
    },
    {
      type: "text",
      id: "communicationClinicianNowName",
      lable: "שם הקלינאי",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinicianNow"],
    },
    {
      type: "text",
      id: "communicationClinicianNowCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["communicationClinicianNow"],
    },
    {
      type: "check",
      id: "correctiveTeacherNow",
      lable: "מורה מתקנת",
      condition: false,
    },
    {
      type: "text",
      id: "correctiveTeacherNowWhen",
      lable: "ממתי?",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacherNow"],
    },
    {
      type: "text",
      id: "correctiveTeacherNowName",
      lable: "שם המורה",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacherNow"],
    },
    {
      type: "text",
      id: "correctiveTeacherNowCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["correctiveTeacherNow"],
    },
    {
      type: "check",
      id: "psychologistNow",
      lable: "פסיכולוג",
      condition: false,
    },
    {
      type: "text",
      id: "psychologistNowWhen",
      lable: "ממתי?",
      kind: "text",
      condition: true,
      conditionById: ["psychologistNow"],
    },
    {
      type: "text",
      id: "psychologistNowName",
      lable: "שם הפסיכולוג",
      kind: "text",
      condition: true,
      conditionById: ["psychologistNow"],
    },
    {
      type: "text",
      id: "psychologistNowCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["psychologistNow"],
    },
    {
      type: "check",
      id: "OrthopticsNow",
      lable: "אורתופטיקה",
      condition: false,
    },
    {
      type: "text",
      id: "OrthopticsNowWhen",
      lable: "ממתי?",
      kind: "text",
      condition: true,
      conditionById: ["OrthopticsNow"],
    },
    {
      type: "text",
      id: "OrthopticsNowName",
      lable: "שם הרופא",
      kind: "text",
      condition: true,
      conditionById: ["OrthopticsNow"],
    },
    {
      type: "text",
      id: "OrthopticsNowCenter",
      lable: "שם המרכז",
      kind: "text",
      condition: true,
      conditionById: ["OrthopticsNow"],
    },
    {
      type: "textArea",
      id: "otherTreatmentNow",
      lable: "אחר-לפרט",
      condition: false
    },
    {
      type: "check",
      id: "hwHelp",
      lable: "האם הילד זקוק לעזרה בשיעורי בית",
      condition: false,
    },
    {
      type: "textArea",
      id: "hwHelpComments",
      lable: "הערות",
      condition: true,
      conditionById:["hwHelp"]
    },
    {
      type: "text",
      id: "hwHelpWho",
      lable: "מי עוזר לו בשיעורי בית",
      kind: "text",
      condition: true,
      conditionById: ["hwHelp"],
    },
    {
      type: "text",
      id: "hwHelpTime ",
      lable: "כמה זמן לוקח לו להשלים את שיעורי הבית",
      kind: "text",
      condition: true,
      conditionById: ["hwHelp"],
    },
    {
      type: "radio",
      id: "hwHardTime",
      lable: "האם זה זמן קשה",
      childrenLables: [
        { id: "hwHardTimeYes", lable: "כן" },
        { id: "hwHardTimeSometimes", lable: "לפעמים" },
        { id: "hwHardTimeNo", lable: "לא" },
      ],
      condition: true,
      conditionById:["hwHelp"]
    }, 
    {
      type: "textArea",
      id: "hwHardTimeComments",
      lable: "הערות",
      condition: false
    },
    {
      type: "label",
      lable: "קשרים חברתיים",
      condition: false,
    },
    {
      type: "check",
      id: "manegeWithFamily",
      lable: "האם הילד מסתדר טוב על כל בני המשפחה",
      condition: false,
    },
    {
      type: "textArea",
      id: "manegeWithFamilyComments",
      lable: "הערות",
      condition: false
    },
    {
      type: "check",
      id: "manegeWithFrainds",
      lable: "האם הילד מסתדר טוב עם ילדים בני גילו",
      condition: false,
    },
    {
      type: "textArea",
      id: "manegeWithFraindsComments",
      lable: "הערות",
      condition: false
    },
    {
      type: "check",
      id: "keepFrainds",
      lable: "האם הוא שומר על חבריו בקלות",
      condition: false,
    },
    {
      type: "textArea",
      id: "keepFraindsComments",
      lable: "לפרט",
      condition: false
    },
    {
      type: "check",
      id: "schoolOnTime",
      lable: "האם הילד מגיע בזמן לבית הספר",
      condition: false
    },
    {
      type: "textArea",
      id: "keepFraindsComments",
      lable: "אם לא,מדוע?",
      condition: true,
      conditionById:["schoolOnTime"],
      conditionByIdValue:false
    }
  ];
  return arr;
}
