import { ChildData } from "./PersonalData";
export default function MedicalData() {
  const arr: ChildData[] = [
    {
      type: "check",
      id: "medication",
      lable: "?האם הילד נוטל תרופות",
      condition: false,
    },
    {
      type: "textArea",
      id: "medicationReasons",
      lable: "?מאלו סיבות",
      condition: true,
      conditionById: ["medication"],
    },
    {
      type: "textArea",
      id: "cMedicalHistory",
      lable: "הסטוריה רפואית של הילד",
      condition: false,
    },

    {
      type: "textArea",
      id: "fMedicalHistory",
      lable: "הסטוריה רפואית של קרובי משפחה",
      condition: false,
    },
    {
      type: "check",
      id: "neurologist",
      lable: "?האם הילד ראה נוירולוג",
      condition: false,
    },
    {
      type: "text",
      id: "neurologistReason",
      lable: "מדוע",
      kind: "text",
      condition: true,
      conditionById: ["neurologist"],
    },
    {
      type: "text",
      id: "neurologistName",
      lable: "שם הנוירולוג",
      kind: "text",
      condition: true,
      conditionById: ["neurologist"],
    },
    {
      type: "check",
      id: "epileptic",
      lable: "?האם הילד עבר התקפים אפילפטיים",
      condition: false,
    },
    {
      type: "text",
      id: "epilepticAge",
      lable: "באיזה גיל",
      condition: true,
      conditionById: ["epileptic"],
      kind: "number",
    },
    {
      type: "check",
      id: "tillNow",
      lable: "?עד היום",
      condition: true,
      conditionById: ["epileptic"],
    },
    {
      type: "text",
      id: "epilepticFrequency",
      lable: "תדירות",
      kind: "text",
      condition: true,
      conditionById: ["epileptic"],
    },
    {
      type: "check",
      id: "epilepticMedication",
      lable: "?האם הילד נמצא בטיפול רפואי?תרופות",
      condition: true,
      conditionById: ["epileptic"],
    },
    {
      type: "textArea",
      id: "epilepticMedicationDetails",
      lable: "נא לפרט",
      condition: true,
      conditionById: ["epilepticMedication"],
    },
    {
      type: "textArea",
      id: "epilepticComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "check",
      id: "visualDisturbance",
      lable: "?האם יש לילד הפרעות ראיה",
      condition: false,
    },
    {
      type: "textArea",
      id: "visualDisturbanceKinds",
      lable: "?אלו",
      condition: true,
      conditionById: ["visualDisturbance"],
    },
    {
      type: "textArea",
      id: "visualDisturbanceComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "check",
      id: "hearingDisturbance",
      lable: "?האם יש לילד הפרעות שמיעה",
      condition: false,
    },
    {
      type: "textArea",
      id: "hearingDisturbanceKinds",
      lable: "?אלו",
      condition: true,
      conditionById: ["hearingDisturbance"],
    },
    {
      type: "textArea",
      id: "hearingDisturbanceComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "check",
      id: "ENTProblems",
      lable: "?האם היו לילד בעיות אף אוזן גרון",
      condition: false,
    },
    {
      type: "text",
      id: "ENTProblemsFrequency",
      lable: "תדירות",
      kind: "text",
      condition: true,
      conditionById: ["ENTProblems"],
    },
    {
      type: "textArea",
      id: "ENTProblemsKinds",
      lable: "?אלו",
      condition: true,
      conditionById: ["ENTProblems"],
    },
    {
      type: "textArea",
      id: "ENTProblemsComments",
      lable: "הערות",
      condition: false,
    },

    {
      type: "label",
      lable: "מידע על שנת הילד",
      condition: false,
    },
    {
      type: "radio",
      id: "troubleSleeping",
      lable: "?האם הילד מתקשה לישון",
      childrenLables: [
        { id: "troubleSleepingYes", lable: "כן" },
        { id: "troubleSleepingSometimes", lable: "לפעמים" },
        { id: "troubleSleepingNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "textArea",
      id: "troubleSleepingKind",
      lable: "אלו",
      condition: true,
      conditionById: ["troubleSleeping"],
      conditionByIdValueRadio: [
        "troubleSleepingYes",
        "troubleSleepingSometimes",
      ],
    },
    {
      type: "textArea",
      id: "troubleSleepingComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "radio",
      id: "escortSleeping",
      lable: "?האם הילד צריך ליווי לשינה",
      childrenLables: [
        { id: "escortSleepingYes", lable: "כן" },
        { id: "escortSleepingSometimes", lable: "לפעמים" },
        { id: "escortSleepingNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "textArea",
      id: "escortSleepingComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "radio",
      id: "sleepWithParents",
      lable: "?האם הילד ישן עם הוריו",
      childrenLables: [
        { id: "sleepWithParentsYes", lable: "כן" },
        { id: "sleepWithParentsSometimes", lable: "לפעמים" },
        { id: "sleepWithParentsNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "textArea",
      id: "sleepWithParentsComments",
      lable: "הערות",
      condition: false,
    },
    {
      type: "radio",
      id: "sleepWithBrothers",
      lable: "?האם הילד ישן עם אחים/אחיות בחדר",
      childrenLables: [
        { id: "sleepWithBrothersYes", lable: "כן" },
        { id: "sleepWithBrothersSometimes", lable: "לפעמים" },
        { id: "sleepWithBrothersNo", lable: "לא" },
      ],
      condition: false,
    },
    {
      type: "textArea",
      id: "sleepWithBrothersComments",
      lable: "הערות",
      condition: false,
    },

    {
      type: "text",
      id: "timeSleeping",
      lable: "מתי הילד הולך לישון",
      kind: "text",
      condition: false,
    },
    {
      type: "text",
      id: "timeWakeUp",
      lable: "מתי הילד קם",
      kind: "text",
      condition: false,
    },
    {
      type: "text",
      id: "timeToSleep",
      lable: "כמה זמן לוקח לו להרדם",
      condition: false,
      kind: "text",
    },
    {
      type: "check",
      id: "wakeUpMood",
      lable: "?האם הילד נמצא במצב רוח טוב כשהוא קם",
      condition: false,
    },
    {
      type: "text",
      id: "howLongWakeUp",
      lable: "כמה זמן לוקח לו ליהיות ער לגמרי",
      condition: true,
      conditionById: ["wakeUpMood"],
      conditionByIdValue: false,
    },
    {
      type: "textArea",
      id: "wakeUpMoodComments",
      lable: "הערות",
      condition: false,
    },

    {
      type: "label",
      lable: "מידע על האכלת הילד",
      condition: false,
    },
    {
      type: "check",
      id: "eatingDisorder",
      lable: "?האם לילד יש הפרעות באכילה",
      condition: false,
    },
    {
      type: "textArea",
      id: "eatingDisorderKinds",
      lable: "?אלו",
      condition: true,
      conditionById: ["eatingDisorder"],
    },
  ];
  return arr;
}
